git remote add bnd1238          https://github.com/bnd1238/spbetu_os_2022_1383.git          # Богданов Егор        
git remote add rafvaliev        https://github.com/rafvaliev/spbetu_os_2022_1383.git        # Валиев Рафис         
git remote add Kirollbas        https://github.com/Kirollbas/spbetu_os_2022_1383.git        # Депрейс Александр    
git remote add vasilisaemakova  https://github.com/vasilisaemakova/spbetu_os_2022_1383.git  # Ермакова Василиса    
git remote add Zhivaev          https://github.com/Zhivaev/spbetu_os_2022_1383.git          # Живаев Максим        
git remote add Skibiduika       https://github.com/Skibiduika/spbetu_os_2022_1383.git       # Заремба Никита       
git remote add Keyrek           https://github.com/Keyrek/spbetu_os_2022_1383.git           # Качабеков Эльхан     
git remote add Cottoffey        https://github.com/Cottoffey/spbetu_os_2022_1383.git        # Кошкин Евгений       
git remote add Pavel7004        https://github.com/Pavel7004/spbetu_os_2022_1383.git        # Ковалёв Павел        
git remote add kulikov02        https://github.com/kulikov02/spbetu_os_2022_1383.git        # Куликов Максим       
git remote add Remaf1n          https://github.com/Remaf1n/spbetu_os_2022_1383.git          # Крутских Глеб        
git remote add gosheno          https://github.com/gosheno/spbetu_os_2022_1383.git          # Малимон Георгий      
git remote add jonx8            https://github.com/jonx8/spbetu_os_2022_1383.git            # Малых Андрей         
git remote add ifdjhxh          https://github.com/ifdjhxh/spbetu_os_2022_1383.git          # Манучарова Ангелина  
git remote add Krig88           https://github.com/Krig88/spbetu_os_2022_1383.git           # Панов Михаил         
git remote add Kupidon4a        https://github.com/Kupidon4a/spbetu_os_2022_1383.git        # Петров Александр     
git remote add samulevich2017   https://github.com/samulevich2017/spbetu_os_2022_1383.git   # Самулевич Степан     
git remote add ubbl-cmd         https://github.com/ubbl-cmd/spbetu_os_2022_1383.git         # Сапожников Алексей   
git remote add Kafkazon         https://github.com/Kafkazon/spbetu_os_2022_1383.git         # Сардинов Михаил      
git remote add EllaSedova       https://github.com/EllaSedova/spbetu_os_2022_1383.git       # Седова Элла          
git remote add moterlode-cmd    https://github.com/moterlode-cmd/spbetu_os_2022_1383.git    # Федорова Оксана      
git remote add necitboss        https://github.com/necitboss/spbetu_os_2022_1383.git        # Харитонов Никита     
git remote add Ars145           https://github.com/Ars145/spbetu_os_2022_1383.git           # Цыганков Арсений     
git remote add sashachernyakova https://github.com/sashachernyakova/spbetu_os_2022_1383.git # Чернякова Александра 
